### ISSUE TITLE
picard doesnt recognize ingame changes

### ISSUE THREAD

**Issue by Nepukadnezar** [jtickle/Picard#20]
so i set up inara correctly to match the ingame totals. 
now when i discard some materials or sell commodities and then launch picard, it doesn't recognize any changes
did i do something wrong? Maybe because i am running on steam and the journal path differs?

**Comment by jtickle** [comment]
I've heard tell that this happens in a few situations.  Can you have a look at your user home directory in Saved Games\Frontier Developments\Elite Dangerous\ and tell me if that contains a bunch of dated log files?  Best I can tell, it's the same path for both Steam and otherwise (and I am on Steam as well).

**Comment by Nepukadnezar** [comment]
yep there are files inside of course, as this is where the journal is located. so you are right.
but i realized that the folder is german here, called "Gespeicherte Spiele" and not saved games. might this be the reason?

**Comment by jtickle** [comment]
Well, I feel bad about the anglo-centrism, but I didn't expect it would localize the Saved Games path.  There will be a release later today (after we can test it a bit) that should locate Gespeicherte Spiele as well, and if not, it will allow you to specify where the journals are.  Thanks for your patience!

**Comment by Nepukadnezar** [comment]
sound great! thanks a lot!

**Comment by Nepukadnezar** [comment]
okay. i just downloaded the new release and tested it. it still doesnt recognize any ingame changes.
i deleted the state file and rechecked with inara. still no joy. what am i doing wrong?

**Comment by jtickle** [comment]
If you wouldn't mind, try the latest version 1.0.6.  There were several issues with the release earlier today.

**Comment by Nepukadnezar** [comment]
hey there! so i tried the newest version and it still didnt work. but i made it work in the end.
so here is what i did:
1. deleted cmdr's .json file
2. restarted picard -> no joy
3. looked into cmdr's .json file, found out that there is no commanders name set
4. put in the correct commanders name
=> works fine!

thanks and sorry for troubling
(where is the donation button :P )
