### ISSUE TITLE
Changes to Inara cause Picard to complain but not sync

### ISSUE THREAD

**Issue by cgoodric** [jtickle/Picard#22]
I made some manual changes in Inara to sync with what's in the game (hadn't gotten Picard to work until yesterday because of pilot error.) Picard now complains that the data is out of sync and in a dialog asks to click OK to syncronize. When I click OK it just continues to complain about data out of sync and throws up the same dialog. No amount of restarting Picard seems to fix this.

**Comment by cgoodric** [comment]
Tried uninstall/reinstall, but uninstall doesn't clean up previous data. Wasn't able to locate picard's data file to delete it.

**Comment by jtickle** [comment]
Hey, thanks for reporting.  The program data is stored in %userprofile%\AppData\Local\TickleSoft.  Delete that folder and it will start from scratch.  I'll see if I can put an option for that into the uninstaller or "repair" mode as well.

**Comment by jtickle** [comment]
The latest release is smarter about reloading that main form, preventing this loop.

https://github.com/jtickle/Picard/releases/tag/v1.0.6-beta
