### ISSUE TITLE
Something very bad with Materials

### ISSUE THREAD

**Issue by nordicpc** [jtickle/Picard#7]
All Current materials have a 0 amount, with -X deltas and showing -X in Elite. Probably has to do with death.

![capture](https://cloud.githubusercontent.com/assets/3279459/22291207/0c678630-e2d3-11e6-9c8d-f3f70e5fd2c7.PNG)

**Comment by jtickle** [comment]
Had a little logic bug with the new journal loading.  Fixed in 960b00ec7b3647dbc154950e4386b5211b25f1c5.
